name: 'Chris & Kana'
favicon: null
layout_spectrum: 0.2384214554913342
typography_spectrum: 0.7368363356217742
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.19149774056859314
  lightness: 0.1659783534705639
  saturation: 0.8204358820803463
  rhythmicContrast: 0.8471750803291798
purpose: []
